### ISSUE TITLE
improve navigation to hide page you're currently in and display header properly

### ISSUE THREAD

**Issue by planetoftheweb** [planetoftheweb/raybo-old#23]

**Comment by hieronymous64** [comment]
PLEASE STOP SPAMMING ME
UNSUBSCRIBE LINKS ARENT WORKING!!

**Comment by planetoftheweb** [comment]
I’m not spamming you,but you’re probably watching one of my repositories. Just click the watch folder at the top of the repo. I’ve been updating the raybo.org repository and you’re currently watching for changes.
